env:
  global:
    - CC_TEST_REPORTER_ID=14ef7d209cc5f02b3e54419aa38f59f125fe14f8b3a050a4253f1de37006b87c

language: node_js

node_js:
  - "8"

branches:
  only:
  - master

install:
  - yarn
  - yarn global add codecov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn jest --coverage
  - codecov
  - cat coverage/lcov.info | yarn coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
