language: node_js

node_js:
  - "8"

branches:
  only:
  - master

install:
  - yarn
  - yarn global add codecov

script:
  - yarn jest --coverage
  - codecov
  - cat coverage/lcov.info | yarn coveralls
